bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               target/dependency/antlr4-runtime-4.13.2.jar,\
               target/dependency/apiguardian-api-1.1.2.jar,\
               target/dependency/asm-9.8.jar,\
               target/dependency/byte-buddy-1.17.5.jar,\
               target/dependency/byte-buddy-agent-1.17.5.jar,\
               target/dependency/checker-qual-3.49.3.jar,\
               target/dependency/commons-codec-1.15.jar,\
               target/dependency/commons-lang3-3.17.0.jar,\
               target/dependency/error_prone_annotations-2.38.0.jar,\
               target/dependency/gson-2.13.1.jar,\
               target/dependency/inez-parser-0.4.1.jar,\
               target/dependency/inez-parser-0.4.1-testing.jar,\
               target/dependency/javax.annotation-api-1.3.2.jar,\
               target/dependency/jul-to-slf4j-1.7.36.jar,\
               target/dependency/konveyor-base-0.2.7-annotations.jar,\
               target/dependency/micrometer-commons-1.14.9.jar,\
               target/dependency/micrometer-observation-1.14.9.jar,\
               target/dependency/nice-xml-messages-3.1.jar,\
               target/dependency/objenesis-3.3.jar,\
               target/dependency/opentest4j-1.3.0.jar,\
               target/dependency/pcollections-4.0.2.jar,\
               target/dependency/pmd-core-7.14.0.jar,\
               target/dependency/pmd-java-7.14.0.jar,\
               target/dependency/Saxon-HE-12.5.jar,\
               target/dependency/slf4j-api-2.0.2.jar,\
               target/dependency/spring-aop-6.2.9.jar,\
               target/dependency/spring-beans-6.2.9.jar,\
               target/dependency/spring-boot-3.5.3.jar,\
               target/dependency/spring-context-6.2.9.jar,\
               target/dependency/spring-core-6.2.9.jar,\
               target/dependency/spring-data-commons-3.5.2.jar,\
               target/dependency/spring-data-keyvalue-3.5.1.jar,\
               target/dependency/spring-expression-6.2.9.jar,\
               target/dependency/spring-jcl-6.2.9.jar,\
               target/dependency/spring-test-6.2.9.jar,\
               target/dependency/spring-tx-6.2.8.jar,\
               target/dependency/xmlresolver-5.2.2.jar,\
               target/dependency/xmlresolver-5.2.2-data.jar,\
               target/dependency/spring-boot-autoconfigure-3.5.3.jar,\
               target/dependency/konveyor-base-0.2.7-runtime.jar,\
               target/dependency/mockito-core-5.18.0.jar,\
               target/dependency/junit-jupiter-api-5.12.1.jar,\
               target/dependency/junit-jupiter-engine-5.12.1.jar,\
               target/dependency/junit-platform-commons-1.12.1.jar,\
               target/dependency/junit-platform-engine-1.12.1.jar,\
               target/dependency/junit-platform-launcher-1.12.1.jar,\
               target/dependency/konveyor-base-0.2.7-testing.jar,\
               target/dependency/httpclient5-5.1.3.jar,\
               target/dependency/httpcore5-5.1.3.jar,\
               target/dependency/httpcore5-h2-5.1.3.jar,\
               target/dependency/konveyor-base-tooling.jar,\
               target/dependency/org.eclipse.core.contenttype-3.9.600.v20241001-1711.jar,\
               target/dependency/org.eclipse.core.jobs-3.15.500.v20250204-0817.jar,\
               target/dependency/org.eclipse.core.runtime-3.33.0.v20250206-0919.jar,\
               target/dependency/org.eclipse.equinox.app-1.7.300.v20250130-0528.jar,\
               target/dependency/org.eclipse.equinox.common-3.20.0.v20250129-1348.jar,\
               target/dependency/org.eclipse.equinox.preferences-3.11.300.v20250130-0533.jar,\
               target/dependency/org.eclipse.equinox.registry-3.12.300.v20250129-1129.jar,\
               target/dependency/org.eclipse.osgi-3.23.0.v20250228-0640.jar,\
               target/dependency/org.osgi.core-6.0.0.jar,\
               target/dependency/org.osgi.service.prefs-1.1.2.jar,\
               target/dependency/osgi.annotation-8.0.1.jar
output.. = target/classes/,target/dependency/
source.. = src/
