#!/bin/bash
set -xe
mkdir -p target/generated-site/markdown target/generated-site/resources target/site
cp README target/generated-site/markdown/index.md
cp pom.xml target/generated-site/resources
cp src/main/antlr4/io/github/magwas/inez/parser/Bridi.g4 target/site/Bridi.txt

