package io.github.magwas.inez;

import java.util.Set;

public interface BridiTestData extends BridiFieldTestData {

	Bridi GO1 = new Bridi(GO1_ID, GO_REPRESENTATION, null);
	Bridi GO2 = new Bridi(GO2_ID, GO_REPRESENTATION, null);
	Bridi SUMTI_IS_A_THING_IS_A_THING = new Bridi(SUMTI_IS_A_THING_IS_A_THING_ID,
			SUMTI_IS_A_THING_IS_A_THING_REPR_NOREFERENCE,
			SUMTI_IS_A_THING_IS_A_THING_REFERENCES);
	Bridi TAUTOLOGY_IS_A_THING = new Bridi(TAUTOLOGY_IS_A_THING_ID,
			TAUTOLOGY_IS_A_THING_REPR, SUMTI_IS_A_THING_IS_A_THING_REFERENCES);
	Bridi THING = new Bridi(THING_ID, THING_REPR, null);
	Bridi THING_CHANGED = new Bridi(THING_ID, "thung", null);
	Bridi THING_GENERATED = new Bridi(InezUtil.createID(THING_REPR), THING_REPR,
			null);
	Bridi SUMTI = new Bridi(SUMTI_ID, SUMTI_REPR, null);
	Bridi NONEXISTENT = new Bridi(NONEXISTENT_ID, NONEXISTENT_REPR, null);
	Bridi BRIDI = new Bridi(BRIDI_ID, BRIDI_REPR, null);
	Bridi IS_A = new Bridi(IS_A_ID, IS_A_REPR, null);
	Bridi ANY = new Bridi(Inez.QUERY_BRIDI_ID, Inez.QUERY_BRIDI_ID, null);

	Bridi SUMTI_IS_A_THING = new Bridi(SUMTI_IS_A_THING_ID, SUMTI_IS_A_THING_REPR,
			SUMTI_IS_A_THING_REFERENCES);
	Bridi SUMTI_IS_A_THING_GENERATED = new Bridi(SUMTI_IS_A_THING_ID,
			SUMTI_IS_A_THING_REPR, SUMTI_IS_A_THING_GENERATED_REFERENCES);
	Bridi SUMTI_IS_A_THING_CHANGED = new Bridi(SUMTI_IS_A_THING_ID,
			SUMTI_IS_A_THING_CHANGED_REPR, SUMTI_IS_A_THING_CHANGED_REFERENCES);
	Bridi TAUTOLOGY = new Bridi(TAUTOLOGY_ID, TAUTOLOGY_REPR,
			SUMTI_IS_A_THING_CHANGED_REFERENCES);
	Bridi THING_IS_A_SUMTI = new Bridi(THING_IS_A_SUMTI_ID, TAUTOLOGY_REPR,
			THING_IS_A_SUMTI_REFERENCES);

	Bridi GOD = new Bridi(GOD_ID, GOD_REPR, null);
	Set<Bridi> SIMPLE_QUERY_OUTPUT = Set.of(TAUTOLOGY,
			SUMTI_IS_A_THING_IS_A_THING, TAUTOLOGY_IS_A_THING, SUMTI_IS_A_THING);

}
