package io.github.magwas.inez;

import java.util.Map;

public interface BridiSetTestData extends BridiTestData {
	BridiSet PARSED_SIMPLE_QUERY = new BridiSet(SIMPLE_QUERY_STRING,
			Map.of(SIMPLE_QUERY_STRING, SIMPLE_QUERY));
	BridiSet PARSED_INPUT = new BridiSet(RECURSIVE_BRIDI_REPR_NOREFERENCE,
			Map.of(SUMTI_REP, SUMTI, THING_REPR, THING, IS_A_REPR, IS_A,
					SUMTI_IS_A_THING_REPR, SUMTI_IS_A_THING_SHORTTERM,
					RECURSIVE_BRIDI_REPR_NOREFERENCE, RECURSIVE_BRIDI_SHORTTERM));

}
