#!/bin/bash
set -xe
if [ x$1 = x ]
then
	VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
else
	VERSION=$1
fi
mvn org.eclipse.tycho:tycho-versions-plugin:4.0.12:set-version -DnewVersion=$VERSION
sed -i 's/application" version="[^"]*"/application" version="'$VERSION'"/' inez.ui.product/Inez.product
